language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://kreuzwerker.pact.dius.com.au/
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "kDIQ08vcjIjp9FV25+OuzYycj12c0ktNqFnQqmOT9ha96Z1swzLMCiziCOGm10zxkx3pKFJ0pVuPS5I8gzAkIolY2h3ttt+ZlkBsJE3QVFYIpRKmCIo2B7+NeICb1DoX8GRIJEYIDnziti4eIpxs4VhH6WSfM4i5xjH7RF8v5yqlXMB2NIHEcgoT3qT9mI7gHsTUv64CL5VzpGf9NVlEChNp+UZtu/vPEOHziz/pRnyqjZshLnCJB+hIkuBkAxEmtXK54iakR9211c5KWynjsQun/hAM/OBjU/dO0OLZawNB2CR2bEWHKhRMJ+Inmfhlc8PWqaunDTAsPumnQ1ymUvqGxpG2C3b/Y0gj+JtHpfdIxrNLHY/XFjIHjcOhHHWE66pjBWD1vIaJGMWkRrgKPddN2lZnhA30JlcLPoF9wagk/r64ltuv4PFuU5tbX+ZpFwPOHVpwXIMuVykeDbIGE5ovbHXtkebNDrHqlj2RGP2k2KPCW4OYWUApBmFm0L2QMkwrkKBNGceRb8bxLvf5wYlBYkrq4Mvw8k1oi/Hx3G7DpWzAv73bo452CiEJr8H9jQxI+6aH4y+Tci91D51at5vIWrq52PwQ2DSYnQbz+l8/0sNiBjZt6/OrNIdjk2IDg9It0wvDfecILSYvQVvweTlqG0xKaE60eRlfmywmtEE="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
